# Generated by Django 5.1.15 on 2026-05-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True, 'ordering': ['-last_seen']},
        ),
    ]
