/* IFINMAIL Client - Mock data layer */

const IFINMAIL_DATA = {
    user: {
        name: 'Alex Mwangi',
        email: 'alex@example.com',
        initials: 'AM'
    },

    contacts: [
        { id: 'c1', name: 'John Mwangi', email: 'john@example.com' },
        { id: 'c2', name: 'Sarah Wanjiku', email: 'sarah@example.com' },
        { id: 'c3', name: 'Peter Kamau', email: 'peter@example.com' },
        { id: 'c4', name: 'Mary Njeri', email: 'mary@example.com' },
        { id: 'c5', name: 'Grace Achieng', email: 'grace@example.com' },
        { id: 'c6', name: 'David Otieno', email: 'david@example.com' }
    ],

    notifications: [
        {
            id: 'n1',
            type: 'email',
            icon: '✉',
            title: 'New email',
            message: 'John sent you an email',
            time: '2 minutes ago',
            read: false
        },
        {
            id: 'n2',
            type: 'security',
            icon: '⚠',
            title: 'Security alert',
            message: 'New login detected',
            time: '20 minutes ago',
            read: false
        },
        {
            id: 'n3',
            type: 'storage',
            icon: '📦',
            title: 'Storage',
            message: 'Mailbox is 80% full',
            time: '1 hour ago',
            read: false
        },
        {
            id: 'n4',
            type: 'email',
            icon: '✉',
            title: 'New email',
            message: 'Sarah Wanjiku sent you an email',
            time: 'Yesterday',
            read: true
        }
    ],

    emails: [
        {
            id: 'e1',
            folder: 'inbox',
            from: { name: 'John Mwangi', email: 'john@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Project meeting tomorrow',
            preview: 'Hello Alex, Can we meet tomorrow at 10 AM to discuss the project?',
            body: 'Hello Alex,\n\nCan we meet tomorrow at 10 AM to discuss the project? I have a few updates on the client requirements and want to go over the timeline.\n\nAlso, please bring the draft proposal so we can finalize the budget section.\n\nRegards,\nJohn',
            date: '2026-08-14T10:32:00',
            read: false,
            starred: true,
            important: false,
            labels: ['work'],
            attachments: [{ name: 'project.pdf', size: '2.4 MB' }]
        },
        {
            id: 'e2',
            folder: 'inbox',
            from: { name: 'Sarah Wanjiku', email: 'sarah@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Invoice #1245',
            preview: 'Hi Alex, please find attached the invoice for last month...',
            body: 'Hi Alex,\n\nPlease find attached the invoice #1245 for last month. Kindly review and let me know if everything is in order.\n\nBest regards,\nSarah',
            date: '2026-08-14T09:21:00',
            read: false,
            starred: false,
            important: false,
            labels: [],
            attachments: [{ name: 'invoice-1245.pdf', size: '180 KB' }]
        },
        {
            id: 'e3',
            folder: 'inbox',
            from: { name: 'Peter Kamau', email: 'peter@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Project files',
            preview: 'Here are the files you requested for the new project...',
            body: 'Here are the files you requested for the new project. Let me know if you need any changes.\n\nCheers,\nPeter',
            date: '2026-08-14T08:45:00',
            read: false,
            starred: true,
            important: true,
            labels: ['work', 'important'],
            attachments: [
                { name: 'requirements.docx', size: '890 KB' },
                { name: 'wireframes.fig', size: '12 MB' }
            ]
        },
        {
            id: 'e4',
            folder: 'inbox',
            from: { name: 'Mary Njeri', email: 'mary@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Hello Alex',
            preview: 'It was great seeing you at the conference...',
            body: 'Hello Alex,\n\nIt was great seeing you at the conference last week. I was wondering if you would be interested in collaborating on the community outreach program.\n\nLet me know what you think.\n\nWarm regards,\nMary',
            date: '2026-08-13T17:15:00',
            read: true,
            starred: false,
            important: false,
            labels: ['personal'],
            attachments: []
        },
        {
            id: 'e5',
            folder: 'inbox',
            from: { name: 'Grace Achieng', email: 'grace@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Meeting notes',
            preview: 'Attached are the notes from Monday meeting...',
            body: 'Attached are the notes from Monday meeting. We captured the action items for each team member.\n\nThanks,\nGrace',
            date: '2026-08-13T11:05:00',
            read: true,
            starred: false,
            important: false,
            labels: ['work'],
            attachments: [{ name: 'meeting-notes.pdf', size: '420 KB' }]
        },
        {
            id: 'e6',
            folder: 'inbox',
            from: { name: 'David Otieno', email: 'david@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Welcome to IFINMAIL',
            preview: 'Your mailbox is ready. Here are some tips to get started...',
            body: 'Welcome to IFINMAIL!\n\nYour mailbox is ready. Here are some tips to get started:\n\n- Use the search bar to find any message\n- Star important messages to find them easily\n- Set up a signature in Settings\n\nEnjoy your new email experience.\n\nIFINMAIL Team',
            date: '2026-08-12T09:00:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: []
        },
        {
            id: 'e7',
            folder: 'snoozed',
            from: { name: 'Sarah Wanjiku', email: 'sarah@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Follow up on proposal',
            preview: 'Checking in on the proposal status...',
            body: 'Hi Alex,\n\nChecking in on the proposal status. Do you have a timeline for when we can expect the final version?\n\nThanks,\nSarah',
            date: '2026-08-11T14:20:00',
            read: true,
            starred: false,
            important: false,
            labels: ['work'],
            attachments: []
        },
        {
            id: 'e8',
            folder: 'sent',
            from: { name: 'Alex Mwangi', email: 'alex@example.com' },
            to: [{ name: 'John Mwangi', email: 'john@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Project update',
            preview: 'Hi John, here is the updated project status...',
            body: 'Hi John,\n\nHere is the updated project status. We are on track for the October delivery.\n\nBest,\nAlex',
            date: '2026-08-14T10:40:00',
            read: true,
            starred: false,
            important: false,
            labels: ['work'],
            attachments: []
        },
        {
            id: 'e9',
            folder: 'sent',
            from: { name: 'Alex Mwangi', email: 'alex@example.com' },
            to: [{ name: 'Sarah Wanjiku', email: 'sarah@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Meeting confirmation',
            preview: 'Confirmed for Thursday at 9 AM. See you there...',
            body: 'Hi Sarah,\n\nConfirmed for Thursday at 9 AM. See you there.\n\nRegards,\nAlex',
            date: '2026-08-14T09:30:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: []
        },
        {
            id: 'e10',
            folder: 'sent',
            from: { name: 'Alex Mwangi', email: 'alex@example.com' },
            to: [{ name: 'Mary Njeri', email: 'mary@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Re: Hello Alex',
            preview: 'Hi Mary, I would love to collaborate...',
            body: 'Hi Mary,\n\nI would love to collaborate on the community outreach program. Let us schedule a call.\n\nBest,\nAlex',
            date: '2026-08-13T18:02:00',
            read: true,
            starred: false,
            important: false,
            labels: ['personal'],
            attachments: []
        },
        {
            id: 'e11',
            folder: 'drafts',
            from: { name: 'Alex Mwangi', email: 'alex@example.com' },
            to: [{ name: 'Peter Kamau', email: 'peter@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Project update',
            preview: 'Hi Peter, I wanted to update you on the project...',
            body: 'Hi Peter,\n\nI wanted to update you on the project. The design team finished the new mockups and we should have a demo ready by Friday.\n\n',
            date: '2026-08-14T10:30:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: [],
            draft: true
        },
        {
            id: 'e12',
            folder: 'drafts',
            from: { name: 'Alex Mwangi', email: 'alex@example.com' },
            to: [{ name: 'Grace Achieng', email: 'grace@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Meeting...',
            preview: 'Hi Grace, are you free for a quick meeting...',
            body: 'Hi Grace,\n\nAre you free for a quick meeting this week to go over the action items?\n\n',
            date: '2026-08-14T09:15:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: [],
            draft: true
        },
        {
            id: 'e13',
            folder: 'drafts',
            from: { name: 'Alex Mwangi', email: 'alex@example.com' },
            to: [],
            cc: [],
            bcc: [],
            subject: '',
            preview: 'New draft',
            body: '',
            date: '2026-08-13T16:40:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: [],
            draft: true
        },
        {
            id: 'e14',
            folder: 'archive',
            from: { name: 'Newsletter Team', email: 'news@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'August newsletter',
            preview: 'Top stories and updates for this month...',
            body: 'Hello,\n\nWelcome to the August newsletter. Here are the top stories and updates for this month.\n\nUnsubscribe anytime.\n\nNewsletter Team',
            date: '2026-08-10T08:00:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: []
        },
        {
            id: 'e15',
            folder: 'archive',
            from: { name: 'Events Desk', email: 'events@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Tech summit tickets',
            preview: 'Early bird tickets are now available...',
            body: 'Early bird tickets for the Tech Summit are now available. Register before the end of the month to get 30% off.\n\nEvents Desk',
            date: '2026-08-08T13:30:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: []
        },
        {
            id: 'e16',
            folder: 'spam',
            from: { name: 'Lottery Winner', email: 'winner@spam.example' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'You have won $1,000,000!!!',
            preview: 'Congratulations! Claim your prize now...',
            body: 'Congratulations! You have been selected as the winner of $1,000,000. Click the link below to claim your prize immediately.\n\nDO NOT share this email with anyone.',
            date: '2026-08-13T03:12:00',
            read: false,
            starred: false,
            important: false,
            labels: [],
            attachments: []
        },
        {
            id: 'e17',
            folder: 'spam',
            from: { name: 'Quick Loans', email: 'loans@spam.example' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Approved: Instant loan offer',
            preview: 'Get cash in 5 minutes with no paperwork...',
            body: 'Get cash in 5 minutes with no paperwork. Low interest rates guaranteed. Apply today!\n\nQuick Loans',
            date: '2026-08-12T22:45:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: []
        },
        {
            id: 'e18',
            folder: 'trash',
            from: { name: 'Old Account', email: 'old@example.com' },
            to: [{ name: 'Alex Mwangi', email: 'alex@example.com' }],
            cc: [],
            bcc: [],
            subject: 'Old notification',
            preview: 'This is an old message that was deleted...',
            body: 'This is an old message that was deleted. It should not have been here anyway.',
            date: '2026-08-01T10:00:00',
            read: true,
            starred: false,
            important: false,
            labels: [],
            attachments: []
        }
    ],

    settings: {
        account: { name: 'Alex Mwangi', email: 'alex@example.com', phone: '+254 712 345 678' },
        mail: { signature: 'Alex Mwangi\nSoftware Engineer\nIFINMAIL', autoReply: false, forwarding: '' },
        notifications: { emailAlerts: true, securityAlerts: true, desktop: false },
        appearance: { theme: 'light', density: 'comfortable' },
        security: { twoFactor: true }
    },

    storage: {
        used: '4.8 GB',
        total: '6 GB',
        percent: 80
    }
};
