#!/usr/bin/env bash
# ifinmail provision.sh - one-command production provisioning.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROVISIONING_DIR="$(dirname "$SCRIPT_DIR")"
DOCKER_DIR="$PROVISIONING_DIR/docker"
ENV_FILE="$PROVISIONING_DIR/.env"
DOMAIN="${DOMAIN:?DOMAIN must be set}"
MAIL_DOMAIN="${MAIL_DOMAIN:-$DOMAIN}"
MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.$DOMAIN}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@$DOMAIN}"
DKIM_SELECTOR="${DKIM_SELECTOR:-default}"
COMPOSE=()
LEGACY_COMPOSE=false

die() {
    echo "ERROR: $*" >&2
    exit 1
}

need_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "$1 is required"
}

normalize_vars() {
    # Normalize domain to lowercase
    DOMAIN="$(echo "$DOMAIN" | tr '[:upper:]' '[:lower:]')"
    # Strip trailing dot (FQDN notation)
    DOMAIN="${DOMAIN%.}"
    MAIL_DOMAIN="$(echo "$MAIL_DOMAIN" | tr '[:upper:]' '[:lower:]')"
    MAIL_DOMAIN="${MAIL_DOMAIN%.}"
    # Validate DKIM_SELECTOR: only lowercase letters, digits, hyphens
    if ! echo "$DKIM_SELECTOR" | grep -qE '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
        echo "WARNING: DKIM_SELECTOR '$DKIM_SELECTOR' is not a valid DNS label. Using 'default'."
        DKIM_SELECTOR="default"
    fi
}

detect_compose() {
    if docker compose version >/dev/null 2>&1; then
        COMPOSE=(docker compose --env-file "$ENV_FILE" -f "$DOCKER_DIR/docker-compose.yml")
    elif command -v docker-compose >/dev/null 2>&1; then
        COMPOSE=(docker-compose --env-file "$ENV_FILE" -f "$DOCKER_DIR/docker-compose.yml")
        LEGACY_COMPOSE=true
    else
        die "docker compose v2 or docker-compose v1 is required"
    fi
}

rand_b64() {
    openssl rand -base64 "$1" | tr -d '\n'
}

rand_urlsafe() {
    openssl rand -base64 "$1" | tr '+/' '-_' | tr -d '=\n'
}

ensure_env() {
    if [ -f "$ENV_FILE" ]; then
        # Strip Windows CRLF line endings if present
        sed -i 's/\r$//' "$ENV_FILE" 2>/dev/null || true
        set -a
        # shellcheck disable=SC1090
        source "$ENV_FILE"
        set +a

        DOMAIN="${DOMAIN:?DOMAIN must be set}"
        MAIL_DOMAIN="${MAIL_DOMAIN:-$DOMAIN}"
        MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.$DOMAIN}"
        ADMIN_EMAIL="${ADMIN_EMAIL:-admin@$DOMAIN}"
        DKIM_SELECTOR="${DKIM_SELECTOR:-default}"

        grep -q '^MAIL_DOMAIN=' "$ENV_FILE" || echo "MAIL_DOMAIN=$MAIL_DOMAIN" >> "$ENV_FILE"
        grep -q '^MAIL_HOSTNAME=' "$ENV_FILE" || echo "MAIL_HOSTNAME=$MAIL_HOSTNAME" >> "$ENV_FILE"
        grep -q '^ADMIN_EMAIL=' "$ENV_FILE" || echo "ADMIN_EMAIL=$ADMIN_EMAIL" >> "$ENV_FILE"
        grep -q '^DKIM_SELECTOR=' "$ENV_FILE" || echo "DKIM_SELECTOR=$DKIM_SELECTOR" >> "$ENV_FILE"
        grep -q '^BACKUP_GPG_PASSPHRASE=' "$ENV_FILE" || echo "BACKUP_GPG_PASSPHRASE=$(rand_b64 32)" >> "$ENV_FILE"
        grep -q '^RSPAMD_CONTROLLER_PASSWORD=' "$ENV_FILE" || echo "RSPAMD_CONTROLLER_PASSWORD=$(rand_b64 24)" >> "$ENV_FILE"
        normalize_vars
        return
    fi

    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by provisioning/scripts/provision.sh
DOMAIN=$DOMAIN
MAIL_DOMAIN=$MAIL_DOMAIN
MAIL_HOSTNAME=$MAIL_HOSTNAME
ADMIN_EMAIL=$ADMIN_EMAIL

COREDNS_IP=127.0.0.1

POSTGRES_ADMIN_PASSWORD=$(rand_b64 36)
APP_DB_PASSWORD=$(rand_urlsafe 24)
DOVECOT_DB_PASSWORD=$(rand_b64 36)
POSTFIX_DB_PASSWORD=$(rand_b64 36)

SECRET_KEY=$(rand_b64 48)
DJANGO_ALLOWED_HOSTS=$DOMAIN,$MAIL_HOSTNAME,api,localhost,127.0.0.1

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=$(rand_urlsafe 24)

RSPAMD_CONTROLLER_PASSWORD=$(rand_b64 24)

DKIM_SELECTOR=$DKIM_SELECTOR

BACKUP_RETENTION_DAYS=30
BACKUP_ENCRYPT=true
BACKUP_GPG_RECIPIENT=${BACKUP_GPG_RECIPIENT:-ifinmail-backup@$DOMAIN}
BACKUP_GPG_PASSPHRASE=$(rand_b64 32)

MONITOR_QUEUE_WARN=50
MONITOR_QUEUE_CRITICAL=200
MONITOR_CERT_WARN_DAYS=30
MONITOR_CERT_CRITICAL_DAYS=7

DJANGO_SUPERUSER_EMAIL=$ADMIN_EMAIL
DJANGO_SUPERUSER_USERNAME=admin
DJANGO_SUPERUSER_PASSWORD=$(rand_b64 16)
EOF

    echo "Created production environment: $ENV_FILE"
}

validate_env() {
    local required=(
        DOMAIN
        MAIL_DOMAIN
        MAIL_HOSTNAME
        ADMIN_EMAIL
        POSTGRES_ADMIN_PASSWORD
        DOVECOT_DB_PASSWORD
        POSTFIX_DB_PASSWORD
        SECRET_KEY
        DJANGO_SUPERUSER_PASSWORD
        APP_DB_PASSWORD
    )
    local missing=false

    for name in "${required[@]}"; do
        local value="${!name:-}"
        if [ -z "$value" ] || [[ "$value" == change_me* ]] || [[ "$value" == dev_* ]] || [[ "$value" == *example.com* ]]; then
            echo "  $name is missing or still uses a placeholder"
            missing=true
        fi
    done

    [ "$missing" = false ] || die "update $ENV_FILE and rerun make provision"
}

ensure_directories() {
    mkdir -p "$DOCKER_DIR/certs/live/$MAIL_HOSTNAME" "$DOCKER_DIR/nginx/www" "$DOCKER_DIR/dkim"
}

ensure_bootstrap_cert() {
    local cert_dir="$DOCKER_DIR/certs/live/$MAIL_HOSTNAME"
    local cert="$cert_dir/fullchain.pem"
    local key="$cert_dir/privkey.pem"
    local dh="$cert_dir/dh.pem"

    mkdir -p "$cert_dir"

    if [ ! -s "$cert" ] || [ ! -s "$key" ]; then
        echo "Creating bootstrap self-signed TLS certificate for $MAIL_HOSTNAME..."
        openssl req -x509 -nodes -newkey rsa:2048 -days 30 \
            -subj "/CN=$MAIL_HOSTNAME" \
            -addext "subjectAltName=DNS:$DOMAIN,DNS:$MAIL_HOSTNAME" \
            -keyout "$key" \
            -out "$cert" >/dev/null 2>&1
        chmod 600 "$key"
    fi

    if [ ! -s "$dh" ]; then
        echo "Generating Dovecot DH parameters..."
        openssl dhparam -out "$dh" 2048 >/dev/null 2>&1
    fi
}

ensure_mta_sts() {
    local www_dir="$DOCKER_DIR/nginx/www"
    local policy_file="$www_dir/.well-known/mta-sts.json"
    local policy_dir
    policy_dir="$(dirname "$policy_file")"

    mkdir -p "$policy_dir"

    # Write policy body without id, then compute stable id from content hash
    cat > "$policy_file" <<INNEREOF
{
  "version": "STSv1",
  "mode": "testing",
  "mx": ["$MAIL_HOSTNAME"],
  "max_age": 1209600
}
INNEREOF

    local mta_sts_id
    mta_sts_id="$(sha256sum "$policy_file" 2>/dev/null | cut -d' ' -f1 | head -c 16 || date +%Y%m%dT%H%M%SZ)"

    echo "MTA-STS policy created in TESTING mode (id: $mta_sts_id)"
    echo "  After verifying TLS delivery for 2+ weeks, change mode to 'enforce' in:"
    echo "  $policy_file"
    echo "  Update the _mta-sts DNS TXT record with the new id after changes."
}

ensure_dkim() {
    local key_path="$DOCKER_DIR/dkim/$DKIM_SELECTOR.$DOMAIN.key"
    local pub_path="${key_path%.key}.pub"

    if [ ! -s "$key_path" ]; then
        echo "Generating DKIM key for $DKIM_SELECTOR._domainkey.$DOMAIN..."
        openssl genrsa -out "$key_path" 2048 >/dev/null 2>&1
        openssl rsa -in "$key_path" -pubout -out "$pub_path" >/dev/null 2>&1
        chmod 600 "$key_path"
    fi

    cat > "$DOCKER_DIR/rspamd/local.d/dkim_signing.conf" <<EOF
allow_username_mismatch = true;
sign_local = true;
use_esld = false;
try_fallback = true;

domain {
  $DOMAIN {
    selector = "$DKIM_SELECTOR";
    path = "/etc/dkim/$DKIM_SELECTOR.$DOMAIN.key";
  }
}
EOF
}

ensure_backup_gpg_key() {
    local gpg_key_id="${BACKUP_GPG_RECIPIENT:-ifinmail-backup@$DOMAIN}"
    local gpg_pass="${BACKUP_GPG_PASSPHRASE:-}"

    if gpg --list-keys "$gpg_key_id" >/dev/null 2>&1; then
        echo "GPG backup key already exists: $gpg_key_id"
        return
    fi

    if [ -z "$gpg_pass" ]; then
        echo "WARNING: BACKUP_GPG_PASSPHRASE not set. Generating passphrase..."
        gpg_pass="$(rand_b64 32)"
        echo "BACKUP_GPG_PASSPHRASE=$gpg_pass" >> "$ENV_FILE"
    fi

    echo "Generating GPG backup key ($gpg_key_id)..."
    cat > /tmp/gpg-batch.txt << GPGBATCH
%echo Generating ifinmail backup GPG key
Key-Type: RSA
Key-Length: 4096
Key-Usage: encrypt
Name-Real: ifinmail Backup
Name-Email: $gpg_key_id
Expire-Date: 0
Passphrase: $gpg_pass
%commit
%echo Done
GPGBATCH

    gpg --batch --pinentry-mode=loopback --passphrase "$gpg_pass" --gen-key /tmp/gpg-batch.txt 2>/dev/null
    rm -f /tmp/gpg-batch.txt

    if gpg --list-keys "$gpg_key_id" >/dev/null 2>&1; then
        local fp
        fp="$(gpg --fingerprint "$gpg_key_id" 2>/dev/null | head -2 | tail -1 | tr -d ' ')"
        echo "GPG backup key generated successfully (fingerprint: $fp)"
    else
        echo "WARNING: Failed to generate GPG backup key. Backup encryption disabled."
    fi
}

obtain_certificate() {
    local live_dir="$DOCKER_DIR/certs/live/$MAIL_HOSTNAME"
    local issuer

    issuer="$(openssl x509 -in "$live_dir/fullchain.pem" -noout -issuer 2>/dev/null || true)"
    if [[ "$issuer" != *"Let's Encrypt"* ]]; then
        echo "Attempting Let's Encrypt certificate for $DOMAIN and $MAIL_HOSTNAME..."
        if "$SCRIPT_DIR/obtain-ssl.sh"; then
            return
        fi

        echo "WARNING: Let's Encrypt issuance failed. The stack is running with a temporary self-signed certificate."
        echo "         Fix DNS/firewall for $DOMAIN and $MAIL_HOSTNAME, then rerun: make provision"
        ensure_bootstrap_cert
    else
        echo "Let's Encrypt certificate already present."
    fi
}

print_dns() {
    local pub_path="$DOCKER_DIR/dkim/$DKIM_SELECTOR.$DOMAIN.pub"
    local dkim_value
    dkim_value="$(grep -v '^-' "$pub_path" | tr -d '\n')"

    # Split DKIM public key into 255-char chunks for DNS TXT record compliance.
    # First chunk includes the prefix, subsequent chunks are pure key material.
    local prefix="v=DKIM1; k=rsa; p="
    local prefix_len=${#prefix}
    local chunk_size=$((255 - prefix_len))
    local dkim_chunks=""
    local remaining="$dkim_value"
    local first=true
    while [ -n "$remaining" ]; do
        if $first; then
            dkim_chunks="${dkim_chunks}\"${prefix}${remaining:0:$chunk_size}\""
            remaining="${remaining:$chunk_size}"
            first=false
        else
            dkim_chunks="${dkim_chunks} \"${remaining:0:255}\""
            remaining="${remaining:255}"
        fi
    done

    cat <<EOF

ifinmail is provisioned for $DOMAIN.

DNS records to publish:
  A      $DOMAIN                  <this server IPv4>
  A      $MAIL_HOSTNAME           <this server IPv4>
  MX     $DOMAIN                  10 $MAIL_HOSTNAME.
  TXT    $DOMAIN                  "v=spf1 mx ~all"
  TXT    _dmarc.$DOMAIN           "v=DMARC1; p=none; rua=mailto:postmaster@$DOMAIN"
  TXT    $DKIM_SELECTOR._domainkey.$DOMAIN $dkim_chunks
  TXT    _mta-sts.$DOMAIN          "v=STSv1; id=$(sha256sum "$DOCKER_DIR/nginx/www/.well-known/mta-sts.json" 2>/dev/null | cut -d' ' -f1 | head -c 16 || date +%Y%m%dT%H%M%SZ)"
  A      mta-sts.$DOMAIN           <this server IPv4>
  PTR    <this server IPv4>       $MAIL_HOSTNAME   (set at your VPS provider — not DNS host)
  AAAA   $DOMAIN                  <this server IPv6>  (if available)
  AAAA   $MAIL_HOSTNAME           <this server IPv6>  (if available)

Reverse DNS (PTR) is critical for mail deliverability. Without it, many
providers (Gmail, Outlook) will reject or spam-folder your messages.
Set reverse DNS for your server's IPv4 address to point to $MAIL_HOSTNAME
through your VPS provider's control panel — not your DNS host.

After DNS is configured, verify with:
  dig +short MX $DOMAIN
  dig +short -x <your-server-ip>
  dig +short TXT $DKIM_SELECTOR._domainkey.$DOMAIN

Useful commands:
  make ps
  make logs
  make down
EOF
}

preflight_checks() {
    echo "Running pre-flight checks..."

    # Check available disk space (need ~2GB for images + data)
    local available_kb
    available_kb="$(df "$PROVISIONING_DIR" | awk 'NR==2 {print $4}')"
    if [ "${available_kb:-0}" -lt 2097152 ]; then
        echo "WARNING: Less than 2GB disk space available. Builds may fail."
    fi

    # Check available RAM (need ~1GB for building and running)
    if [ -f /proc/meminfo ]; then
        local mem_avail_kb
        mem_avail_kb="$(awk '/MemAvailable/ {print $2}' /proc/meminfo)"
        if [ "${mem_avail_kb:-0}" -lt 1048576 ]; then
            echo "WARNING: Less than 1GB RAM available. Services may be OOM-killed."
        fi
    fi

    # Check if Docker daemon is running
    if ! docker info >/dev/null 2>&1; then
        die "Docker daemon is not running. Start it with: systemctl start docker"
    fi

    # Check if required ports are already in use
    for port in 25 80 143 443 465 587 993; do
        if ss -tlnp 2>/dev/null | grep -q ":${port} "; then
            echo "WARNING: Port $port is already in use. The stack may fail to bind."
        fi
    done

    echo "Pre-flight checks complete."
}

ensure_kernel_settings() {
    if [ -r /proc/sys/vm/overcommit_memory ] && [ "$(cat /proc/sys/vm/overcommit_memory)" != "1" ]; then
        echo "Enabling vm.overcommit_memory=1 for Redis background saves..."
        sysctl -w vm.overcommit_memory=1 >/dev/null 2>&1 || \
            echo "WARNING: Could not set vm.overcommit_memory=1; Redis may warn during startup."
    fi

    if [ -d /etc/sysctl.d ] && [ -w /etc/sysctl.d ]; then
        cat > /etc/sysctl.d/99-ifinmail.conf <<EOF
vm.overcommit_memory = 1
EOF
    fi
}

main() {
    echo "======================================"
    echo "  ifinmail production provisioning"
    echo "======================================"

    need_cmd docker
    need_cmd openssl
    need_cmd gpg
    detect_compose

    ensure_env
    set -a
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    set +a
    DOMAIN="${DOMAIN:?DOMAIN must be set}"
    MAIL_DOMAIN="${MAIL_DOMAIN:-$DOMAIN}"
    MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.$DOMAIN}"
    ADMIN_EMAIL="${ADMIN_EMAIL:-admin@$DOMAIN}"
    DKIM_SELECTOR="${DKIM_SELECTOR:-default}"
    normalize_vars
    validate_env
    preflight_checks
    ensure_kernel_settings
    ensure_directories
    ensure_bootstrap_cert
    ensure_mta_sts
    ensure_dkim
    ensure_backup_gpg_key

    echo "Building images..."
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" build --pull)

    if [ "$LEGACY_COMPOSE" = true ]; then
        (cd "$DOCKER_DIR" && "${COMPOSE[@]}" rm -fs api postfix dovecot rspamd >/dev/null 2>&1 || true)
    fi

    echo "Starting stack..."
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" up -d)

    obtain_certificate
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" restart postfix dovecot nginx)

    echo "Starting certbot auto-renewal service..."
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" --profile certbot up -d certbot) || true

    echo "Current service status:"
    (cd "$DOCKER_DIR" && "${COMPOSE[@]}" ps)

    print_dns
}

main "$@"
