#!/usr/bin/env bash
# ifinmail setup-wizard.sh — interactive first-run configuration
# Generates provisioning/.env with user-provided domain and auto-generated secrets.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROVISIONING_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROVISIONING_DIR/.env"

die() {
    echo "ERROR: $*" >&2
    exit 1
}

rand_b64() {
    openssl rand -base64 "$1" | tr -d '\n'
}

rand_urlsafe() {
    openssl rand -base64 "$1" | tr '+/' '-_' | tr -d '=\n'
}

banner() {
    echo ""
    echo "======================================"
    echo "  ifinmail — Setup Wizard"
    echo "======================================"
    echo ""
}

validate_domain() {
    local domain="$1"
    # Basic RFC 1035 hostname validation
    if ! echo "$domain" | grep -qE '^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)+$'; then
        die "Invalid domain: $domain"
    fi
    # Reject obvious placeholders
    case "$domain" in
        example.com|example.org|example.net|yourdomain.com|change_me*|test.com|localhost)
            die "Please provide your real domain, not '$domain'."
            ;;
    esac
}

validate_email() {
    local email="$1"
    if ! echo "$email" | grep -qE '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'; then
        die "Invalid email: $email"
    fi
}

check_existing_env() {
    if [ -f "$ENV_FILE" ]; then
        echo "An existing configuration was found at provisioning/.env"
        read -rp "Overwrite? [y/N] " confirm
        if [ "${confirm,,}" != "y" ]; then
            echo "Keeping existing file. Run 'make provision' to continue."
            exit 0
        fi
        # Back up the old file
        cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
        echo "  Backed up previous .env."
    fi
}

check_dns() {
    local domain="$1"
    if host "$domain" >/dev/null 2>&1; then
        echo "  DNS resolves: yes"
    else
        echo "  DNS resolves: not yet (you'll need to configure DNS before mail flows)"
        echo "    Expected A records: $domain and mail.$domain → <this server's IP>"
    fi
}

main() {
    banner
    check_existing_env

    # --- Collect user input ---
    echo "Domain configuration"
    echo "  Enter the domain name you want to host email for."
    read -rp "  Domain: " DOMAIN
    DOMAIN="${DOMAIN:-}"
    validate_domain "$DOMAIN"

    local default_mail_hostname="mail.$DOMAIN"
    read -rp "  Mail hostname [$default_mail_hostname]: " MAIL_HOSTNAME
    MAIL_HOSTNAME="${MAIL_HOSTNAME:-$default_mail_hostname}"

    local default_admin_email="admin@$DOMAIN"
    read -rp "  Admin email [$default_admin_email]: " ADMIN_EMAIL
    ADMIN_EMAIL="${ADMIN_EMAIL:-$default_admin_email}"
    validate_email "$ADMIN_EMAIL"

    echo ""
    echo "Security"
    local default_admin_user="admin"
    read -rp "  Admin username [$default_admin_user]: " ADMIN_USERNAME
    ADMIN_USERNAME="${ADMIN_USERNAME:-$default_admin_user}"

    echo ""
    echo "Monitoring & Alerts (optional)"
    read -rp "  Sentry DSN (leave blank to skip): " SENTRY_DSN
    read -rp "  Alert webhook URL (leave blank to skip): " MONITOR_ALERT_WEBHOOK

    echo ""
    echo "Backup"
    read -rp "  GPG key email for backup encryption [ifinmail-backup@$DOMAIN]: " BACKUP_GPG_RECIPIENT
    BACKUP_GPG_RECIPIENT="${BACKUP_GPG_RECIPIENT:-ifinmail-backup@$DOMAIN}"

    echo ""
    echo "---"
    echo "Generating secrets..."

    # --- Generate secrets ---
    local SECRET_KEY
    SECRET_KEY="$(rand_b64 48)"

    local POSTGRES_ADMIN_PASSWORD
    POSTGRES_ADMIN_PASSWORD="$(rand_b64 36)"

    local APP_DB_PASSWORD
    APP_DB_PASSWORD="$(rand_urlsafe 24)"

    local DOVECOT_DB_PASSWORD
    DOVECOT_DB_PASSWORD="$(rand_b64 36)"

    local POSTFIX_DB_PASSWORD
    POSTFIX_DB_PASSWORD="$(rand_b64 36)"

    local REDIS_PASSWORD
    REDIS_PASSWORD="$(rand_urlsafe 24)"

    local DJANGO_SUPERUSER_PASSWORD
    DJANGO_SUPERUSER_PASSWORD="$(rand_b64 16)"

    local BACKUP_GPG_PASSPHRASE
    BACKUP_GPG_PASSPHRASE="$(rand_b64 32)"

    local RSPAMD_CONTROLLER_PASSWORD
    RSPAMD_CONTROLLER_PASSWORD="$(rand_b64 24)"

    echo "  Done."

    # --- Write .env file ---
    umask 077
    cat > "$ENV_FILE" <<EOF
# ifinmail environment — generated by setup-wizard.sh on $(date -Iseconds)
# WARNING: this file contains secrets. Do not commit to version control.

# --- Domain ---
DOMAIN=$DOMAIN
MAIL_DOMAIN=$DOMAIN
MAIL_HOSTNAME=$MAIL_HOSTNAME
ADMIN_EMAIL=$ADMIN_EMAIL

# --- CoreDNS (reserved for future DNS server integration) ---
COREDNS_IP=127.0.0.1

# --- PostgreSQL ---
POSTGRES_ADMIN_PASSWORD=$POSTGRES_ADMIN_PASSWORD
APP_DB_PASSWORD=$APP_DB_PASSWORD
DOVECOT_DB_PASSWORD=$DOVECOT_DB_PASSWORD
POSTFIX_DB_PASSWORD=$POSTFIX_DB_PASSWORD

# --- Django ---
SECRET_KEY=$SECRET_KEY
DJANGO_ALLOWED_HOSTS=$DOMAIN,$MAIL_HOSTNAME,api,localhost,127.0.0.1

# --- Redis ---
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=$REDIS_PASSWORD

RSPAMD_CONTROLLER_PASSWORD=$RSPAMD_CONTROLLER_PASSWORD

# --- DKIM ---
DKIM_SELECTOR=default

# --- Django superuser ---
DJANGO_SUPERUSER_USERNAME=$ADMIN_USERNAME
DJANGO_SUPERUSER_EMAIL=$ADMIN_EMAIL
DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD

# --- Backup ---
BACKUP_RETENTION_DAYS=30
BACKUP_ENCRYPT=true
BACKUP_GPG_RECIPIENT=$BACKUP_GPG_RECIPIENT
BACKUP_GPG_PASSPHRASE=$BACKUP_GPG_PASSPHRASE

# --- Monitor thresholds ---
MONITOR_QUEUE_WARN=50
MONITOR_QUEUE_CRITICAL=200
MONITOR_CERT_WARN_DAYS=30
MONITOR_CERT_CRITICAL_DAYS=7

# --- Security ---
CSRF_TRUSTED_ORIGINS=https://$DOMAIN,https://$MAIL_HOSTNAME
AXES_FAILURE_LIMIT=5
SECURE_HSTS_SECONDS=3600
EOF

    # Append optional fields if provided
    if [ -n "$SENTRY_DSN" ]; then
        cat >> "$ENV_FILE" <<EOF

# --- Sentry ---
SENTRY_DSN=$SENTRY_DSN
SENTRY_ENVIRONMENT=production
EOF
    fi

    if [ -n "$MONITOR_ALERT_WEBHOOK" ]; then
        echo "MONITOR_ALERT_WEBHOOK=$MONITOR_ALERT_WEBHOOK" >> "$ENV_FILE"
    fi

    echo ""
    echo "Configuration saved to: $ENV_FILE"
    echo ""
    echo "---"
    echo "  Domain:        $DOMAIN"
    echo "  Mail hostname: $MAIL_HOSTNAME"
    echo "  Admin email:   $ADMIN_EMAIL"
    echo "  Admin user:    $ADMIN_USERNAME"
    echo "  Admin password: $DJANGO_SUPERUSER_PASSWORD"
    echo "---"
    echo ""
    echo "Save the admin password above — you'll need it to log in."
    echo ""

    check_dns "$DOMAIN"

    echo ""
    echo "Next step:"
    echo "  make provision"
    echo ""
}

main "$@"
