# Generated by Django 5.1.15 on 2026-05-28 19:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DKIMKey',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('selector', models.CharField(default='default', max_length=64)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dkim_keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('mx_verified', models.BooleanField(default=False)),
                ('spf_verified', models.BooleanField(default=False)),
                ('dkim_verified', models.BooleanField(default=False)),
                ('dmarc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'domains',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
