# Generated by Django 5.1.15 on 2026-05-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSProviderConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('cloudflare', 'Cloudflare'),
                            ('porkbun', 'Porkbun'),
                            ('digitalocean', 'DigitalOcean'),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ('credentials', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'dns_provider_config',
                'managed': False,
            },
        ),
    ]
