"""add messages table

Revision ID: 401194956f3d
Revises: e9e8b03f298b
Create Date: 2026-05-21 06:47:05.080636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401194956f3d'
down_revision: Union[str, Sequence[str], None] = 'e9e8b03f298b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mailbox_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('from_addr', sa.String(length=255), nullable=False),
    sa.Column('to_addrs', sa.Text(), nullable=False),
    sa.Column('cc_addrs', sa.Text(), nullable=True),
    sa.Column('bcc_addrs', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('read', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('starred', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('has_attachments', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('folder', sa.String(length=32), server_default=sa.text("'INBOX'"), nullable=False),
    sa.Column('in_reply_to', sa.String(length=255), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
