mail_location = maildir:/var/mail/%d/%n
mail_privileged_group = vmail
mail_uid = vmail
mail_gid = vmail

mbox_write_locks = fcntl

mail_plugins = $mail_plugins quota

# Full filesystem access
valid_chroot_dirs = /var/mail

# User database
userdb {
  driver = sql
  args = /etc/dovecot/conf.d/dovecot-sql.conf.ext
}
