# Generated by Django 5.1.15 on 2026-05-28 19:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('source', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'aliases',
                'db_table': 'aliases',
                'ordering': ['domain', 'source'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('local_part', models.CharField(max_length=128)),
                ('quota_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mailboxes',
                'managed': False,
            },
        ),
    ]
