# DMARC module settings
# https://rspamd.com/doc/modules/dmarc.html
reporting {
    enabled = true;
    # Send aggregate reports daily (default: 0 = disabled)
    report_active = 1d;
    # Maximum size of a DMARC report (default: 10MB)
    max_report_size = 10Mb;
    # Send report if coverage reaches this fraction (default: 0.99)
    min_report_coverage = 0.95;
    # Retry failed reports for this long (default: 2d)
    retry = 2d;
    # Use local Postfix to send reports
    send_mail_from = "noreply-dmarc";
}
