# Generated by Django 5.1.15 on 2026-05-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifinmail_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storedfile',
            new_name='ifinmail_st_entity__d2b0a7_idx',
            old_name='ifinmail_st_entity_93fa19_idx',
        ),
    ]
